"""
SDN Controller — top-level application.

Wires together the OpenFlow server, MAC learning, topology discovery,
load balancer, traffic shaper and failover manager.

Control plane logic
-------------------
  Packet-In handler:
    1. Learn source MAC → port.
    2. If destination MAC is known, install a proactive flow rule and
       forward this packet directly (avoid future Packet-In for this flow).
    3. If destination unknown, flood on spanning-tree ports.

  Port-Status handler:
    Delegates to FailoverManager which updates topology and re-routes.

  Topology discovery:
    LLDP packets generated by the controller are injected via Packet-Out
    on each switch port.  When a switch receives an LLDP and sends Packet-In,
    the source (dpid, port) pair is recorded as a link.

REST API (plain HTTP on port 8080):
    GET  /topology          → JSON topology snapshot
    GET  /switches          → connected switches
    GET  /flows             → active flow stats (per switch, from OF multipart)
    GET  /lb                → load balancer stats
    GET  /failover          → active failures
    POST /lb/backend        → add backend {ip, port, mac, weight}
    DELETE /lb/backend/<ip>/<port>  → remove backend
"""

from __future__ import annotations

import http.server
import json
import logging
import struct
import threading
import time
from typing import Optional

from .channel import OpenFlowServer, SwitchConnection
from .failover import FailoverManager
from .load_balancer import LoadBalancer, Policy
from .mac_table import MACTable
from .openflow import (
    OFPType, OFPPortNo,
    PacketIn, PortStatus,
    action_output, flow_mod, packet_out,
    _build_oxm_match, OFPFlowModCommand,
    multipart_request, OFPMultipartType,
    barrier_request,
)
from .topology import TopologyGraph
from .traffic_shaper import TrafficShaper

log = logging.getLogger(__name__)

_FLOOD_PRIORITY  = 1
_FORWARD_PRIORITY= 10
_LB_PRIORITY     = 20
_FLOW_IDLE       = 30    # seconds
_LLDP_ETH_TYPE   = 0x88CC
_LLDP_INTERVAL   = 5.0   # seconds between LLDP floods


class SDNController:
    """
    Main controller application.

    Parameters
    ----------
    of_port : int     OpenFlow listen port (default 6653).
    rest_port : int   REST API port (default 8080).
    vip : str         Virtual IP for the load balancer.
    vport : int       Virtual TCP port for the load balancer.
    lb_policy : str   "round_robin" or "least_conn".
    """

    def __init__(
        self,
        of_port:   int = 6653,
        rest_port: int = 8080,
        vip:       str = "10.0.0.100",
        vport:     int = 80,
        lb_policy: str = "round_robin",
    ) -> None:
        self._topo     = TopologyGraph()
        self._macs     = MACTable()
        self._lb       = LoadBalancer(vip=vip, vport=vport,
                                      policy=Policy(lb_policy))
        self._shaper   = TrafficShaper()
        self._failover = FailoverManager(
            topology=self._topo,
            install_fn=self._install_rules,
        )
        self._server   = OpenFlowServer(
            port      = of_port,
            on_connect    = self._on_switch_connect,
            on_disconnect = self._on_switch_disconnect,
        )
        self._server.register(OFPType.PACKET_IN,   self._handle_packet_in)
        self._server.register(OFPType.PORT_STATUS, self._handle_port_status)
        self._server.register(OFPType.MULTIPART_REPLY, self._handle_stats_reply)

        self._rest_port   = rest_port
        self._rest_server: Optional[http.server.HTTPServer] = None
        self._xid         = 1
        self._xid_lock    = threading.Lock()

        # LLDP flood thread
        self._lldp_thread: Optional[threading.Thread] = None

    # ── lifecycle ──────────────────────────────────────────────────────────────

    def start(self) -> None:
        self._server.start()
        self._failover.start()
        self._lldp_thread = threading.Thread(
            target=self._lldp_loop, daemon=True, name="lldp"
        )
        self._lldp_thread.start()
        self._start_rest()
        log.info("SDN controller started  OF=%d  REST=%d", 6653, self._rest_port)

    def stop(self) -> None:
        self._failover.stop()
        self._server.stop()
        if self._rest_server:
            self._rest_server.shutdown()

    # ── switch lifecycle ──────────────────────────────────────────────────────

    def _on_switch_connect(self, conn: SwitchConnection) -> None:
        log.info("Switch connected: %s", conn)
        self._topo.add_switch(conn.dpid)
        # Install a table-miss rule: send all unmatched packets to controller
        match   = _build_oxm_match({})
        actions = action_output(OFPPortNo.CONTROLLER)
        rule    = flow_mod(
            xid=self._next_xid(), command=OFPFlowModCommand.ADD,
            priority=0, match=match, actions=actions,
            idle_timeout=0, hard_timeout=0,
        )
        conn.send(rule)

    def _on_switch_disconnect(self, conn: SwitchConnection) -> None:
        log.info("Switch disconnected: %s", conn)
        self._topo.remove_switch(conn.dpid)
        self._macs.clear_dpid(conn.dpid)

    # ── Packet-In ─────────────────────────────────────────────────────────────

    def _handle_packet_in(self, conn: SwitchConnection, msg: bytes) -> None:
        try:
            pkt = PacketIn.from_bytes(msg)
        except Exception:
            return

        if len(pkt.data) < 14:
            return

        eth_dst = ":".join(f"{b:02x}" for b in pkt.data[0:6])
        eth_src = ":".join(f"{b:02x}" for b in pkt.data[6:12])
        eth_type = struct.unpack_from("!H", pkt.data, 12)[0]

        # LLDP: record the inter-switch link
        if eth_type == _LLDP_ETH_TYPE:
            self._process_lldp(conn, pkt)
            return

        in_port = pkt.in_port
        dpid    = conn.dpid

        # Learn source
        self._macs.learn(dpid, eth_src, in_port)
        src_loc = self._topo.host_location(eth_src)
        if src_loc is None:
            self._topo.update_host(eth_src, dpid, in_port)
        self._failover.record_heartbeat(dpid, in_port)

        # Check load balancer (TCP SYN to VIP)
        if eth_type == 0x0800 and len(pkt.data) >= 34:
            ip_proto  = pkt.data[23]
            dst_ip    = ".".join(str(b) for b in pkt.data[30:34])
            if ip_proto == 6 and dst_ip == self._lb.vip:
                tcp_dst = struct.unpack_from("!H", pkt.data, 36)[0]
                if tcp_dst == self._lb.vport:
                    src_ip  = ".".join(str(b) for b in pkt.data[26:30])
                    tcp_src = struct.unpack_from("!H", pkt.data, 34)[0]
                    self._lb_redirect(conn, pkt, src_ip, tcp_src)
                    return

        # Normal L2 forwarding
        out_port = self._macs.lookup(dpid, eth_dst)
        if out_port is not None:
            self._install_l2_flow(conn, eth_src, eth_dst, in_port, out_port)
            self._send_packet(conn, pkt.buffer_id, in_port, out_port, pkt.data)
        else:
            self._flood(conn, pkt)

    # ── L2 flow installation ──────────────────────────────────────────────────

    def _install_l2_flow(
        self,
        conn: SwitchConnection,
        eth_src: str,
        eth_dst: str,
        in_port: int,
        out_port: int,
    ) -> None:
        match   = _build_oxm_match({"in_port": in_port, "eth_dst": eth_dst})
        actions = action_output(out_port)
        rule    = flow_mod(
            xid=self._next_xid(), command=OFPFlowModCommand.ADD,
            priority=_FORWARD_PRIORITY, match=match, actions=actions,
            idle_timeout=_FLOW_IDLE, hard_timeout=0,
        )
        conn.send(rule)

    def _install_rules(self, dpid: int, rules: list[dict]) -> None:
        """Called by FailoverManager to push new routes."""
        conns = self._server.connections()
        conn  = next((c for c in conns if c.dpid == dpid), None)
        if conn is None:
            return
        for rule in rules:
            match_fields = rule.get("match", {})
            match   = _build_oxm_match(match_fields)
            actions = b"".join(
                action_output(a["port"])
                for a in rule.get("actions", [])
                if a.get("type") == "OUTPUT"
            )
            fm = flow_mod(
                xid=self._next_xid(),
                command=OFPFlowModCommand.ADD,
                priority=rule.get("priority", 10),
                match=match, actions=actions,
                idle_timeout=rule.get("idle_timeout", 60),
            )
            conn.send(fm)

    # ── load-balancer redirect ────────────────────────────────────────────────

    def _lb_redirect(
        self,
        conn: SwitchConnection,
        pkt: PacketIn,
        client_ip: str,
        client_port: int,
    ) -> None:
        backend = self._lb.get_backend(client_ip, client_port)
        if backend is None:
            log.warning("No backend available for %s:%d", client_ip, client_port)
            return
        # Install a flow rule that rewrites dst IP/port to the backend
        # (simplified: just forward to the backend MAC's port)
        dst_loc = self._topo.host_location(backend.mac)
        if dst_loc is None:
            return
        out_port = dst_loc.port
        match    = _build_oxm_match({"eth_type": 0x0800, "ipv4_dst": self._lb.vip,
                                     "ip_proto": 6, "tcp_dst": self._lb.vport})
        actions  = action_output(out_port)
        fm       = flow_mod(
            xid=self._next_xid(), command=OFPFlowModCommand.ADD,
            priority=_LB_PRIORITY, match=match, actions=actions,
            idle_timeout=_FLOW_IDLE,
        )
        conn.send(fm)
        self._send_packet(conn, pkt.buffer_id, pkt.in_port, out_port, pkt.data)

    # ── flooding ──────────────────────────────────────────────────────────────

    def _flood(self, conn: SwitchConnection, pkt: PacketIn) -> None:
        tree_ports = self._topo.spanning_tree_ports()
        st_for_dpid = tree_ports.get(conn.dpid, set())
        all_ports   = self._topo.switch_ports(conn.dpid)
        # Flood on spanning-tree ports, excluding the ingress port
        flood_ports = (st_for_dpid | all_ports) - {pkt.in_port}
        if not flood_ports:
            self._send_packet(conn, pkt.buffer_id, pkt.in_port, OFPPortNo.FLOOD, pkt.data)
            return
        for port in flood_ports:
            self._send_packet(conn, 0xFFFFFFFF, pkt.in_port, port, pkt.data)

    # ── Port-Status ───────────────────────────────────────────────────────────

    def _handle_port_status(self, conn: SwitchConnection, msg: bytes) -> None:
        try:
            ps = PortStatus.from_bytes(msg)
        except Exception:
            return
        self._failover.on_port_status(conn.dpid, ps)

    # ── Stats ─────────────────────────────────────────────────────────────────

    def _handle_stats_reply(self, conn: SwitchConnection, msg: bytes) -> None:
        pass   # parsed on demand by REST handler

    def request_port_stats(self, conn: SwitchConnection) -> None:
        conn.send(multipart_request(
            self._next_xid(), OFPMultipartType.PORT_STATS,
        ))

    # ── LLDP ──────────────────────────────────────────────────────────────────

    def _lldp_loop(self) -> None:
        while True:
            time.sleep(_LLDP_INTERVAL)
            self._send_lldp_probes()

    def _send_lldp_probes(self) -> None:
        for conn in self._server.connections():
            dpid  = conn.dpid
            ports = self._topo.switch_ports(dpid)
            for port in ports:
                lldp = self._build_lldp(dpid, port)
                po   = packet_out(
                    xid=self._next_xid(),
                    buffer_id=0xFFFFFFFF,
                    in_port=OFPPortNo.CONTROLLER,
                    actions=action_output(port),
                    data=lldp,
                )
                conn.send(po)

    @staticmethod
    def _build_lldp(dpid: int, port: int) -> bytes:
        """Minimal LLDP frame encoding dpid and port in TLVs."""
        dst_mac = bytes.fromhex("0180c2000000")
        src_mac = dpid.to_bytes(8, "big")[2:]   # last 6 bytes of dpid
        eth     = dst_mac + src_mac + struct.pack("!H", _LLDP_ETH_TYPE)
        # Chassis ID TLV: type=1 len=7 subtype=4 (MAC) + MAC
        chassis = struct.pack("!H", (1 << 9) | 7) + b"\x04" + src_mac
        # Port ID TLV: type=2 len=5 subtype=2 (ifName) + port bytes
        port_tlv = struct.pack("!HBI", (2 << 9) | 5, 2, port)
        # TTL TLV: type=3 len=2 value=120
        ttl = struct.pack("!HH", (3 << 9) | 2, 120)
        # End TLV
        end = struct.pack("!H", 0)
        return eth + chassis + port_tlv + ttl + end

    def _process_lldp(self, conn: SwitchConnection, pkt: PacketIn) -> None:
        """Extract origin dpid+port from LLDP payload and record link."""
        data = pkt.data
        if len(data) < 14 + 9:
            return
        off = 14   # skip Ethernet header
        # Chassis ID TLV: extract last 6 bytes = MAC (our dpid encoding)
        tlv_header = struct.unpack_from("!H", data, off)[0]
        tlv_len    = tlv_header & 0x1FF
        src_mac    = data[off + 2: off + 2 + 6]
        src_dpid   = int.from_bytes(b"\x00\x00" + src_mac, "big")
        off       += 2 + tlv_len
        # Port ID TLV
        tlv_header = struct.unpack_from("!H", data, off)[0]
        src_port   = struct.unpack_from("!I", data, off + 3)[0]

        dst_dpid = conn.dpid
        dst_port = pkt.in_port
        self._topo.add_link(src_dpid, src_port, dst_dpid, dst_port)

    # ── helpers ───────────────────────────────────────────────────────────────

    def _send_packet(
        self,
        conn: SwitchConnection,
        buffer_id: int,
        in_port: int,
        out_port: int,
        data: bytes,
    ) -> None:
        actions = action_output(out_port)
        po = packet_out(
            xid=self._next_xid(),
            buffer_id=buffer_id,
            in_port=in_port,
            actions=actions,
            data=data if buffer_id == 0xFFFFFFFF else b"",
        )
        conn.send(po)

    def _next_xid(self) -> int:
        with self._xid_lock:
            xid = self._xid
            self._xid = (self._xid + 1) & 0xFFFFFFFF
            return xid

    # ── REST API ──────────────────────────────────────────────────────────────

    def _start_rest(self) -> None:
        ctrl = self

        class Handler(http.server.BaseHTTPRequestHandler):
            def log_message(self, *args):
                pass   # suppress access log to stdout

            def do_GET(self):
                body = ctrl._rest_get(self.path)
                if body is None:
                    self.send_response(404); self.end_headers()
                    return
                data = json.dumps(body).encode()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", len(data))
                self.end_headers()
                self.wfile.write(data)

            def do_POST(self):
                length = int(self.headers.get("Content-Length", 0))
                body   = json.loads(self.rfile.read(length)) if length else {}
                result = ctrl._rest_post(self.path, body)
                data   = json.dumps(result).encode()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", len(data))
                self.end_headers()
                self.wfile.write(data)

            def do_DELETE(self):
                result = ctrl._rest_delete(self.path)
                data   = json.dumps(result).encode()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(data)

        self._rest_server = http.server.HTTPServer(("0.0.0.0", self._rest_port), Handler)
        t = threading.Thread(target=self._rest_server.serve_forever, daemon=True, name="rest")
        t.start()

    def _rest_get(self, path: str):
        if path == "/topology":
            return self._topo.to_dict()
        if path == "/switches":
            return [{"dpid": f"0x{c.dpid:016x}", "addr": list(c.address)}
                    for c in self._server.connections()]
        if path == "/lb":
            return self._lb.stats()
        if path == "/lb/backends":
            return self._lb.stats()["backends"]
        if path == "/failover":
            return {"active_failures": self._failover.active_failures()}
        if path == "/shaper":
            return self._shaper.stats()
        if path == "/macs":
            result = {}
            for dpid in self._topo.all_switches():
                result[f"0x{dpid:016x}"] = self._macs.snapshot(dpid)
            return result
        return None

    def _rest_post(self, path: str, body: dict):
        if path == "/lb/backend":
            b = self._lb.add_backend(
                ip=body["ip"], port=int(body["port"]),
                mac=body["mac"], weight=int(body.get("weight", 1)),
            )
            return {"status": "ok", "backend": {"ip": b.ip, "port": b.port}}
        if path == "/shaper/meter":
            mid = self._shaper.add_rate_limit(
                rate_kbps=int(body["rate_kbps"]),
                burst_kbps=int(body.get("burst_kbps", 0)),
            )
            return {"status": "ok", "meter_id": mid}
        return {"status": "unknown path"}

    def _rest_delete(self, path: str):
        parts = path.strip("/").split("/")
        if len(parts) == 3 and parts[0] == "lb" and parts[1] == "backend":
            ip   = parts[2]
            port = int(parts[3]) if len(parts) > 3 else 80
            self._lb.remove_backend(ip, port)
            return {"status": "ok"}
        return {"status": "not found"}
